# Generated by Django 4.2.7 on 2025-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='후원 금액')),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='후원자 이름')),
                ('message', models.TextField(blank=True, null=True, verbose_name='응원 메시지')),
                ('payment_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='결제 키')),
                ('order_id', models.CharField(max_length=200, unique=True, verbose_name='주문 ID')),
                ('payment_status', models.CharField(choices=[('PENDING', '대기중'), ('DONE', '완료'), ('CANCELED', '취소'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='결제 상태')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='결제 수단')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='후원 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '후원',
                'verbose_name_plural': '후원',
                'ordering': ['-created_at'],
            },
        ),
    ]
