# Generated by Django 4.2.7 on 2025-11-10 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="completed_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="name",
            field=models.CharField(
                blank=True, help_text="검사 응시자 이름", max_length=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="assessmentanswer",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="assessment.assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessmentanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="assessment.assessmentquestion",
            ),
        ),
        migrations.AddField(
            model_name="assessmentanswer",
            name="value",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="1~5 리커트 척도 응답값",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="dimension",
            field=models.CharField(
                choices=[
                    ("COMM", "커뮤니케이션·협업"),
                    ("RESP", "책임감·성실성"),
                    ("PROB", "문제해결·논리"),
                    ("GROW", "성장지향·학습의지"),
                    ("STRE", "스트레스·정서안정"),
                    ("ADAP", "조직적응·대인관계"),
                    ("VALI", "타당도(주의/과장)"),
                ],
                default="COMM",
                help_text="이 문항이 속한 역량 축",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="is_reverse",
            field=models.BooleanField(
                default=False, help_text="역코딩 문항인지 여부 (3,6,10,13,16,20 등)"
            ),
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="number",
            field=models.PositiveSmallIntegerField(
                default=3, help_text="문항 번호 (1~20)", unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentquestion",
            name="text",
            field=models.CharField(
                default="질문 내용 없음", help_text="문항 내용", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="adaptation",
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="assessment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="assessment.assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="attention_check_pass",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="communication",
            field=models.DecimalField(decimal_places=2, default="3.00", max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="exaggeration_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="growth",
            field=models.DecimalField(decimal_places=2, default="3.00", max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="problem_solving",
            field=models.DecimalField(decimal_places=2, default="3.00", max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="responsibility",
            field=models.DecimalField(decimal_places=2, default="3.00", max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="stress",
            field=models.DecimalField(decimal_places=2, default="3.00", max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="type_label",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="assessmentanswer",
            unique_together={("assessment", "question")},
        ),
    ]
