# Generated by Django 4.2.7 on 2025-11-25 01:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessment_completed_at_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.assessmentquestion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='dimension',
            field=models.CharField(choices=[('COMM', '커뮤니케이션·협업'), ('RESP', '책임감·성실성'), ('PROB', '문제해결·논리'), ('GROW', '성장지향·학습의지'), ('STRE', '스트레스·정서안정'), ('ADAP', '조직적응·대인관계'), ('VALI', '타당도')], max_length=5),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='is_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment.assessment'),
            preserve_default=False,
        ),
    ]
