# Generated by Django 4.2.7 on 2025-11-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='면접관 이름 (예: 김OO 팀장)', max_length=100)),
                ('role', models.CharField(help_text='면접관 직무 (예: 시니어 백엔드 개발자)', max_length=100)),
                ('personality', models.CharField(choices=[('friendly', '우호적'), ('aggressive', '압박형'), ('technical', '기술 집착형'), ('practical', '실무형'), ('silent', '과묵형'), ('beginner', '주니어형'), ('cto_level', 'CTO 수준'), ('hr_focused', '인사팀')], max_length=20, unique=True)),
                ('system_prompt', models.TextField(help_text="GPT API에 시스템 메시지로 주입할 프롬프트 (예: '당신은 매우 꼼꼼한 시니어 개발자입니다...')")),
            ],
        ),
        migrations.CreateModel(
            name='InterviewExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interviewer', models.ForeignKey(help_text='이 질문을 한 면접관', on_delete=django.db.models.deletion.CASCADE, to='interview.interviewer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_topic', models.CharField(help_text='면접 주제 (예: React, Django)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('started', '시작됨'), ('completed', '완료됨')], default='started', max_length=20)),
                ('interviewers', models.ManyToManyField(help_text='이 세션에 배정된 면접관들', related_name='interview_sessions', to='interview.interviewer')),
            ],
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='InterviewMessage',
        ),
        migrations.DeleteModel(
            name='InterviewResult',
        ),
        migrations.AddField(
            model_name='interviewexchange',
            name='session',
            field=models.ForeignKey(help_text='이 대화가 속한 전체 면접 세션', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='interview.interviewsession'),
        ),
    ]
