# Generated by Django 4.2.7 on 2025-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_interviewer_interviewexchange_interviewsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="total_questions",
            field=models.IntegerField(
                default=10, help_text="이 세션에서 진행할 총 질문 횟수"
            ),
        ),
    ]
