# Generated by Django 4.2.7 on 2025-12-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_interviewsession_total_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="final_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interviewer",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="interviewer",
            name="personality",
            field=models.CharField(
                choices=[
                    ("hr", "인사팀 (인성/문화)"),
                    ("tech", "기술팀 (직무/지식)"),
                    ("exp", "관련경험팀 (실무/경험)"),
                ],
                help_text="소속 팀 (hr, tech, exp 중 선택)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="interviewer",
            name="role",
            field=models.CharField(
                help_text="직함 (예: 인사팀장, 수석 개발자)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="interviewer",
            name="system_prompt",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="interviewers",
            field=models.ManyToManyField(
                related_name="sessions", to="interview.interviewer"
            ),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="job_topic",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="status",
            field=models.CharField(default="started", max_length=20),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="total_questions",
            field=models.IntegerField(default=10),
        ),
    ]
